POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVkdXJhbiIsImlkIjoiNWZjNzE0MGFkNWVmNzU3MTgxZDA0NmM3IiwiaWF0IjoxNjA2ODgzMTExfQ.rg6q48g44OrdhOK_VD_sajH-9H7lhJTv3B3vlQWHoLo

{
  "title": "Blog 2",
  "author": "Me",
  "url": "myblog2.com",
  "likes": "10"
}
